Repository classroomio/classroomio, pull requests merged in 2023-12, with the labels that each got.

#65 feat: added refresh button to generate new slug.
  apps/dashboard/src/lib/components/Course/components/Settings/index.svelte
Labels: good first issue

#95 fix: Corrected Duplicate Response Messages
  apps/dashboard/src/lib/components/Org/Settings/TeamMembers.svelte
  apps/dashboard/src/routes/org/[slug]/community/[slug]/+page.svelte
  apps/dashboard/src/routes/org/[slug]/community/ask/+page.svelte
Labels: bug, good first issue

#96 fix: Duplicate Invite Issues.
  apps/dashboard/src/lib/components/Org/Settings/TeamMembers.svelte
Labels: bug, good first issue

#92 feat: unit tests for utils functions
  apps/dashboard/.babelrc
  apps/dashboard/babel.config.cjs
  apps/dashboard/jest.config.ts
  apps/dashboard/package.json
  apps/dashboard/src/lib/components/Course/components/Lesson/Exercises/NewExerciseModal.svelte
  apps/dashboard/src/lib/components/Course/components/Lesson/Materials/index.svelte
  apps/dashboard/src/lib/utils/functions/IsSubmissionEarly.spec.js
  apps/dashboard/src/lib/utils/functions/course.spec.ts
  apps/dashboard/src/lib/utils/functions/course.ts
  apps/dashboard/src/lib/utils/functions/date.spec.ts
  apps/dashboard/src/lib/utils/functions/formatYoutubeVideo.spec.ts
  apps/dashboard/src/lib/utils/functions/genUniqueId.spec.js
  apps/dashboard/src/lib/utils/functions/generateSlug.spec.js
  apps/dashboard/src/lib/utils/functions/generateUUID.spec.ts
  apps/dashboard/src/lib/utils/functions/getCurrencyFormatter.spec.ts
  apps/dashboard/src/lib/utils/functions/isObject.spec.ts
  apps/dashboard/src/lib/utils/functions/isObject.ts
  apps/dashboard/src/lib/utils/functions/org.spec.ts
  apps/dashboard/src/lib/utils/functions/removeDuplicate.spec.js
  apps/dashboard/src/lib/utils/functions/showAppsSideBar.spec.js
  apps/dashboard/src/lib/utils/functions/string.spec.ts
  apps/dashboard/src/lib/utils/functions/validateEmail.spec.js
  apps/dashboard/tsconfig.json
  pnpm-lock.yaml
Labels: enhancement, good first issue

#118 feat: Add course card context menu on course page
  apps/dashboard/src/lib/components/Courses/components/Card/index.svelte
  apps/dashboard/src/lib/components/Courses/index.svelte
Labels: good first issue, frontend

#123 feat(page): hide email of people in a course
  apps/dashboard/src/routes/courses/[id]/people/+page.svelte
Labels: good first issue
