Repository classroomio/classroomio, pull requests merged in 2024-05, with the labels that each got.

#296 feat: Grade exercises with AI
  apps/dashboard/src/lib/components/Course/components/Lesson/Exercise/EditMode.svelte
  apps/dashboard/src/lib/components/Course/components/Lesson/Exercise/MarkExerciseModal.svelte
  apps/dashboard/src/lib/components/Course/components/Lesson/Exercise/Preview.svelte
  apps/dashboard/src/lib/components/Course/components/Lesson/Exercise/ViewMode.svelte
  apps/dashboard/src/lib/components/Course/components/Lesson/Exercise/constants.js
  apps/dashboard/src/lib/components/Course/components/Lesson/Exercise/index.svelte
  apps/dashboard/src/lib/components/Course/components/Lesson/Exercises/index.svelte
  apps/dashboard/src/lib/components/Course/components/Lesson/store/answers.js
  apps/dashboard/src/lib/components/CourseLandingPage/components/PricingSection.svelte
  apps/dashboard/src/lib/components/Courses/components/Card/index.svelte
  apps/dashboard/src/lib/components/Form/Select.svelte
  apps/dashboard/src/lib/components/Form/TextField.svelte
  apps/dashboard/src/lib/components/Modal/index.svelte
  apps/dashboard/src/lib/components/PageNav/index.svelte
  apps/dashboard/src/lib/components/Question/CheckboxQuestion/index.svelte
  apps/dashboard/src/lib/components/Question/Grade.svelte
  apps/dashboard/src/lib/components/Question/RadioQuestion/index.svelte
  apps/dashboard/src/lib/components/Question/ReasonBox.svelte
  apps/dashboard/src/lib/components/Question/TextareaQuestion/index.svelte
  apps/dashboard/src/lib/components/QuestionContainer/index.svelte
  apps/dashboard/src/lib/utils/services/courses/index.ts
  apps/dashboard/src/lib/utils/services/submissions/index.ts
  apps/dashboard/src/lib/utils/translations/de.json
  apps/dashboard/src/lib/utils/translations/en.json
  apps/dashboard/src/lib/utils/translations/es.json
  apps/dashboard/src/lib/utils/translations/fr.json
  apps/dashboard/src/lib/utils/translations/hi.json
  apps/dashboard/src/lib/utils/translations/pt.json
  apps/dashboard/src/lib/utils/translations/ru.json
  apps/dashboard/src/lib/utils/translations/vi.json
  apps/dashboard/src/routes/api/completion/gradingprompt/+server.js
  apps/dashboard/src/routes/courses/[id]/lessons/[...lessonParams]/+page.svelte
  apps/dashboard/src/routes/courses/[id]/submissions/+page.svelte
  apps/dashboard/static/ai.svg
  apps/dashboard/static/comment.svg
  packages/shared/src/plans/data.json
  supabase/migrations/20240509080635_ai_grading.sql
Labels: core team work

#314 fix: Fix empty lesson title bug
  apps/dashboard/src/lib/components/Course/components/Lesson/store/lessons.ts
  apps/dashboard/src/lib/components/Course/components/Navigation/index.svelte
  apps/dashboard/src/lib/utils/functions/validator.js
  apps/dashboard/src/routes/courses/[id]/+page.svelte
  apps/dashboard/src/routes/courses/[id]/lessons/+page.svelte
Labels: bug

#309 feat: Create self paced and live courses
  apps/classroomio-com/src/lib/Navigation/Navigation.svelte
  apps/classroomio-com/src/routes/new/+page.server.ts
  apps/dashboard/src/lib/components/Course/components/Ceritficate/Design.svelte
  apps/dashboard/src/lib/components/Course/components/Lesson/AddLessonModal.svelte
  apps/dashboard/src/lib/components/Course/components/Lesson/Exercise/DeleteConfirmation.svelte
  apps/dashboard/src/lib/components/Course/components/Lesson/Exercise/GradingLoader.svelte
  apps/dashboard/src/lib/components/Course/components/Lesson/Exercise/ViewMode.svelte
  apps/dashboard/src/lib/components/Course/components/Lesson/NewLessonModal.svelte
  apps/dashboard/src/lib/components/Course/components/Lesson/store/exercise.js
  apps/dashboard/src/lib/components/Course/components/Lesson/store/lessons.ts
  apps/dashboard/src/lib/components/Course/components/Navigation/index.svelte
  apps/dashboard/src/lib/components/Course/components/Settings/index.svelte
  apps/dashboard/src/lib/components/Course/components/Settings/store.js
  apps/dashboard/src/lib/components/Course/store.ts
  apps/dashboard/src/lib/components/CourseContainer/index.svelte
  apps/dashboard/src/lib/components/Courses/components/Card/index.svelte
  apps/dashboard/src/lib/components/Courses/components/List/index.svelte
  apps/dashboard/src/lib/components/Courses/components/NewCourseModal/index.svelte
  apps/dashboard/src/lib/components/Courses/index.svelte
  apps/dashboard/src/lib/components/Courses/store.ts
  apps/dashboard/src/lib/components/LMS/components/Learning.svelte
  apps/dashboard/src/lib/components/Org/LandingPage/index.svelte
  apps/dashboard/src/lib/components/Tabs/index.svelte
  apps/dashboard/src/lib/utils/services/courses/index.ts
  apps/dashboard/src/lib/utils/translations/de.json
  apps/dashboard/src/lib/utils/translations/en.json
  apps/dashboard/src/lib/utils/translations/es.json
  apps/dashboard/src/lib/utils/translations/fr.json
  apps/dashboard/src/lib/utils/translations/hi.json
  apps/dashboard/src/lib/utils/translations/pt.json
  apps/dashboard/src/lib/utils/translations/ru.json
  apps/dashboard/src/lib/utils/translations/vi.json
  apps/dashboard/src/lib/utils/types/index.ts
  apps/dashboard/src/routes/courses/[id]/+page.svelte
  apps/dashboard/src/routes/courses/[id]/lessons/+page.svelte
  apps/dashboard/src/routes/courses/[id]/marks/+page.svelte
  apps/dashboard/src/routes/courses/[id]/submissions/+page.svelte
  apps/dashboard/src/routes/lms/mylearning/+page.svelte
  apps/dashboard/src/routes/org/[slug]/+layout.svelte
  apps/dashboard/src/routes/org/[slug]/courses/+page.svelte
  supabase/migrations/20240516153823_course_type.sql
Labels: core team work

#324 feat: Auto move to the next question
  apps/dashboard/src/lib/components/Course/components/Lesson/Exercise/EditMode.svelte
  apps/dashboard/src/lib/components/Course/components/Lesson/Exercise/ViewMode.svelte
  apps/dashboard/src/lib/components/Course/components/Lesson/Exercise/functions.js
  apps/dashboard/src/lib/components/Question/CheckboxQuestion/index.svelte
  apps/dashboard/src/lib/components/Question/RadioQuestion/index.svelte
  apps/dashboard/src/lib/components/Question/TextareaQuestion/index.svelte
  apps/dashboard/src/routes/org/[slug]/courses/+page.svelte
Labels: core team work

#327 feat: Implemeted the Roadmap page
  apps/classroomio-com/src/lib/Faq/Faq.svelte
  apps/classroomio-com/src/lib/Footer/Footer.svelte
  apps/classroomio-com/src/lib/PageSignupCTA/index.svelte
  apps/classroomio-com/src/lib/Timeline/Timeline.svelte
  apps/classroomio-com/src/routes/(redirects)/demo/+page.server.ts
  apps/classroomio-com/src/routes/(redirects)/devanddesign/+page.server.ts
  apps/classroomio-com/src/routes/(redirects)/discord/+page.server.ts
  apps/classroomio-com/src/routes/(redirects)/github/+page.server.ts
  apps/classroomio-com/src/routes/(redirects)/new/+page.server.ts
  apps/classroomio-com/src/routes/(redirects)/privacy/+page.server.ts
  apps/classroomio-com/src/routes/(redirects)/signup/+page.server.ts
  apps/classroomio-com/src/routes/(redirects)/tos/+page.server.ts
  apps/classroomio-com/src/routes/docs/+layout.ts
  apps/classroomio-com/src/routes/docs/+page.svelte
  apps/classroomio-com/src/routes/roadmap/+page.svelte
  apps/classroomio-com/static/roadmap-one.svg
  apps/classroomio-com/static/roadmap-two.svg
Labels: core team work

#326 chore: simplify grading for self paced course
  apps/classroomio-com/src/routes/(redirects)/docs/+layout.svelte
  apps/classroomio-com/src/routes/(redirects)/docs/+page.svelte
  apps/dashboard/src/lib/components/Course/components/Lesson/Exercise/Preview.svelte
  apps/dashboard/src/lib/components/Course/components/Lesson/Exercise/ViewMode.svelte
  apps/dashboard/src/lib/components/CourseContainer/index.svelte
  apps/dashboard/src/lib/components/Question/CheckboxQuestion/index.svelte
  apps/dashboard/src/lib/components/Question/RadioQuestion/index.svelte
  apps/dashboard/src/lib/components/Question/TextareaQuestion/index.svelte
  apps/dashboard/src/lib/components/TextEditor/TinymceSvelte/index.svelte
  apps/dashboard/src/lib/utils/functions/validator.js
  apps/dashboard/src/lib/utils/translations/de.json
  apps/dashboard/src/lib/utils/translations/en.json
  apps/dashboard/src/lib/utils/translations/es.json
  apps/dashboard/src/lib/utils/translations/fr.json
  apps/dashboard/src/lib/utils/translations/hi.json
  apps/dashboard/src/lib/utils/translations/pt.json
  apps/dashboard/src/lib/utils/translations/ru.json
  apps/dashboard/src/lib/utils/translations/vi.json
  apps/dashboard/src/routes/courses/[id]/+page.svelte
  apps/dashboard/src/routes/courses/[id]/lessons/+page.svelte
  apps/dashboard/src/routes/courses/[id]/submissions/+page.svelte
  apps/dashboard/static/js/tinymce/skins/content/light/content.js
  apps/dashboard/static/js/tinymce/skins/content/light/content.min.css
Labels: bug

#331 fix: fixed the generate exercise with AI bug
  apps/dashboard/src/lib/components/Course/components/Lesson/Exercises/NewExerciseModal.svelte
Labels: bug

#335 fix: enable lesson cascade delete
  apps/dashboard/src/lib/components/Course/components/Lesson/store/lessons.ts
  apps/dashboard/src/lib/utils/translations/de.json
  apps/dashboard/src/lib/utils/translations/en.json
  apps/dashboard/src/lib/utils/translations/es.json
  apps/dashboard/src/lib/utils/translations/fr.json
  apps/dashboard/src/lib/utils/translations/hi.json
  apps/dashboard/src/lib/utils/translations/pt.json
  apps/dashboard/src/lib/utils/translations/ru.json
  apps/dashboard/src/lib/utils/translations/vi.json
  apps/dashboard/src/routes/courses/[id]/lessons/+page.svelte
  supabase/migrations/20231115082347_remote_schema.sql
  supabase/migrations/20240528050512_cascade_delete_lesson.sql
  supabase/seed.sql
Labels: bug

#339 feat: No way to reset select in community page
  apps/dashboard/src/lib/components/Org/Community/index.svelte
  apps/dashboard/src/lib/utils/translations/de.json
  apps/dashboard/src/lib/utils/translations/en.json
  apps/dashboard/src/lib/utils/translations/es.json
  apps/dashboard/src/lib/utils/translations/fr.json
  apps/dashboard/src/lib/utils/translations/hi.json
  apps/dashboard/src/lib/utils/translations/pt.json
  apps/dashboard/src/lib/utils/translations/ru.json
  apps/dashboard/src/lib/utils/translations/vi.json
Labels: bug

#340 fix: Prevent hypen at start or end of organzation or domain name
  apps/dashboard/src/lib/components/Org/Settings/OrgSettings.svelte
  apps/dashboard/src/lib/utils/functions/validator.js
Labels: good first issue
