Repository classroomio/classroomio, pull requests merged in 2024-03, with the labels that each got.

#180 fix: get lighthouse score to 100
  apps/classroomio-com/src/app.html
  apps/classroomio-com/src/lib/Body/Section.svelte
  apps/classroomio-com/src/lib/Faq/Faq.svelte
  apps/classroomio-com/src/lib/Footer/Footer.svelte
  apps/classroomio-com/src/lib/Hero/Hero.svelte
  apps/classroomio-com/src/lib/Hero/ImageCompare.svelte
  apps/classroomio-com/src/lib/MoreFeatures/MoreFeatures.svelte
  apps/classroomio-com/src/lib/Navigation/Navigation.svelte
  apps/classroomio-com/src/lib/Pricing/Pricing.svelte
  apps/classroomio-com/src/routes/blog/+page.svelte
  apps/classroomio-com/src/routes/blog/[slug]/+page.svelte
  apps/classroomio-com/static/cio-hero-imac.png
  apps/classroomio-com/static/cio-hero-imac.webp
  apps/classroomio-com/static/landing-page-builder.png
  apps/classroomio-com/static/landing-page-builder.webp
  apps/classroomio-com/static/logo-512.svg
Labels: bug

#173 docs: Improve sign-up documentation for ClassroomIO
  apps/docs/pages/quickstart/signup.mdx
Labels: documentation

#174 docs: Customizing your organization
  apps/docs/pages/howtoguides/customize-organization.mdx
  apps/docs/pages/howtoguides/images/customize-organization.png
  apps/docs/pages/howtoguides/images/customize-organization.webp
  apps/docs/pages/howtoguides/images/domain-setup-one.webp
  apps/docs/pages/howtoguides/images/domain-setup-three.webp
  apps/docs/pages/howtoguides/images/domain-setup-two.webp
Labels: documentation

#223 feat: Trigger add modal in People page via url
  apps/dashboard/src/lib/components/Course/components/People/InvitationModal.svelte
  apps/dashboard/src/lib/components/Course/components/People/store.js
  apps/dashboard/src/routes/courses/[id]/people/+page.svelte
Labels: good first issue
