Repository classroomio/classroomio, pull requests merged in 2024-02, with the labels that each got.

#162 fix: meta tag on docs are broken
  apps/dashboard/src/routes/+layout.server.ts
  apps/docs/theme.config.tsx
  supabase/seed.sql
Labels: backend

#163 feat: upon clicking Save, redirect to Exercises page
  apps/dashboard/src/lib/components/Course/components/Lesson/Exercise/index.svelte
Labels: good first issue

#164 chore: seed db
  supabase/seed.sql
Labels: backend

#166 docs: write documentation on how to login
  README.md
  apps/docs/pages/contributor-guides/_meta.json
  apps/docs/pages/contributor-guides/demo-accounts.mdx
  supabase/seed.sql
Labels: documentation

#157 feat: add dropdown to community ask
  README.md
  apps/dashboard/src/app.postcss
  apps/dashboard/src/lib/components/Buttons/Close/index.svelte
  apps/dashboard/src/lib/components/Navigation/lms.svelte
  apps/dashboard/src/lib/components/Org/Community/Loader.svelte
  apps/dashboard/src/lib/components/Org/Community/index.svelte
  apps/dashboard/src/lib/components/Org/Settings/OrgSettings.svelte
  apps/dashboard/src/lib/utils/functions/theme.ts
  apps/dashboard/src/lib/utils/functions/validator.js
  apps/dashboard/src/lib/utils/services/org/index.ts
  apps/dashboard/src/routes/+layout.server.ts
  apps/dashboard/src/routes/+layout.svelte
  apps/dashboard/src/routes/lms/community/[slug]/+page.svelte
  apps/dashboard/src/routes/lms/community/ask/+page.svelte
  apps/dashboard/src/routes/org/[slug]/community/[slug]/+page.svelte
  apps/dashboard/src/routes/org/[slug]/community/ask/+page.svelte
  supabase/migrations/20240212110855_add_courseid_to_community_question.sql
  supabase/seed.sql
Labels: enhancement

#168 feat: add classroomio's server to the monorepo
  README.md
  apps/backend/.dockerignore
  apps/backend/.gitignore
  apps/backend/Dockerfile
  apps/backend/README.md
  apps/backend/certificate.html
  apps/backend/course.html
  apps/backend/fly.toml
  apps/backend/lesson.html
  apps/backend/package-lock.json
  apps/backend/package.json
  apps/backend/server.js
  apps/backend/src/routes/downloadCertificate.js
  apps/backend/src/routes/downloadCourse.js
  apps/backend/src/routes/downloadLesson.js
  apps/backend/src/routes/uploadVideo.js
  apps/backend/src/utils/certificate.js
  apps/backend/src/utils/course.js
  apps/backend/src/utils/genUniqueId.js
  apps/backend/src/utils/lesson.js
  apps/backend/src/utils/puppeteer.js
  apps/backend/src/utils/supabase.js
  apps/backend/src/utils/upload.js
  pnpm-lock.yaml
Labels: core team work
