Repository classroomio/classroomio, pull requests merged in 2024-12, with the labels that each got.

#514 feat: add recommended blog post depending on current post tags
  apps/classroomio-com/src/lib/Blog/BlogListItem.svelte
  apps/classroomio-com/src/lib/types.ts
  apps/classroomio-com/src/routes/blog/+page.svelte
  apps/classroomio-com/src/routes/blog/+page.ts
  apps/classroomio-com/src/routes/blog/[slug]/+page.svelte
  apps/classroomio-com/src/routes/blog/[slug]/+page.ts
Labels: hacktoberfest

#530 feat: automatically detect language on server and translate UI
  .vscode/settings.json
  apps/dashboard/src/lib/components/AuthUI/index.svelte
  apps/dashboard/src/lib/components/Org/LandingPage/index.svelte
  apps/dashboard/src/lib/components/Org/VerifyEmail/VerifyEmailModal.svelte
  apps/dashboard/src/lib/utils/functions/appSetup.ts
  apps/dashboard/src/lib/utils/functions/translations.ts
  apps/dashboard/src/lib/utils/functions/validator.ts
  apps/dashboard/src/lib/utils/services/courses/index.ts
  apps/dashboard/src/lib/utils/services/org/index.ts
  apps/dashboard/src/lib/utils/translations/de.json
  apps/dashboard/src/lib/utils/translations/en.json
  apps/dashboard/src/lib/utils/translations/es.json
  apps/dashboard/src/lib/utils/translations/fr.json
  apps/dashboard/src/lib/utils/translations/hi.json
  apps/dashboard/src/lib/utils/translations/pt.json
  apps/dashboard/src/lib/utils/translations/ru.json
  apps/dashboard/src/lib/utils/translations/vi.json
  apps/dashboard/src/routes/+layout.server.ts
  apps/dashboard/src/routes/+layout.svelte
  apps/dashboard/src/routes/+layout.ts
  apps/dashboard/src/routes/invite/t/[hash]/+page.svelte
  apps/dashboard/src/routes/login/+page.svelte
  apps/dashboard/src/routes/org/[slug]/setup/+page.ts
  apps/dashboard/src/routes/signup/+page.svelte
Labels: core team work

#532 feat: organisation home page with analytics
  apps/dashboard/src/lib/components/Analytics/ActivityCard.svelte
  apps/dashboard/src/lib/components/Icons/AudienceIcon.svelte
  apps/dashboard/src/lib/components/Icons/CourseIcon.svelte
  apps/dashboard/src/lib/utils/translations/de.json
  apps/dashboard/src/lib/utils/translations/en.json
  apps/dashboard/src/lib/utils/translations/es.json
  apps/dashboard/src/lib/utils/translations/fr.json
  apps/dashboard/src/lib/utils/translations/hi.json
  apps/dashboard/src/lib/utils/translations/pt.json
  apps/dashboard/src/lib/utils/translations/ru.json
  apps/dashboard/src/lib/utils/translations/vi.json
  apps/dashboard/src/lib/utils/types/analytics.ts
  apps/dashboard/src/routes/api/analytics/dash/+server.ts
  apps/dashboard/src/routes/lms/+page.svelte
  apps/dashboard/src/routes/org/[slug]/+page.svelte
  supabase/migrations/20241016235827_student_analytics.sql
  supabase/migrations/20241231154543_dashboard_stats.sql
Labels: needs triage
