Repository classroomio/classroomio, pull requests merged in 2024-04, with the labels that each got.

#233 feat: add math equation support in Tinymce
  apps/backend/package.json
  apps/backend/server.js
  apps/backend/src/routes/katex.js
  apps/dashboard/src/lib/components/TextEditor/index.svelte
  apps/dashboard/src/lib/utils/functions/tinymce/plugins.ts
  apps/dashboard/src/routes/courses/[id]/lessons/+layout.svelte
  pnpm-lock.yaml
Labels: core team work

#229 feat: implement onboarding setup page
  apps/dashboard/src/lib/components/Icons/StepDoneIcon.svelte
  apps/dashboard/src/lib/components/Org/SideBar.svelte
  apps/dashboard/src/routes/org/[slug]/setup/+page.svelte
  apps/dashboard/src/routes/org/[slug]/setup/+page.ts
Labels: core team work

#242 chore: New hero section on landing page
  apps/classroomio-com/src/app.css
  apps/classroomio-com/src/lib/Hero/Hero.svelte
  apps/classroomio-com/src/lib/Hero/HeroBackground.svelte
  apps/classroomio-com/src/lib/Testimonial/Testimonial.svelte
  apps/classroomio-com/static/cio-hero-imac.webp
  apps/classroomio-com/static/cio-hero.webp
Labels: core team work

#243 feat: Moved nodemailer to the backend
  README.md
  apps/backend/.env.example
  apps/backend/package.json
  apps/backend/server.js
  apps/backend/src/routes/sendEmail.js
  apps/backend/src/utils/getTransporter.js
  apps/backend/src/utils/withEmailTemplate.js
  apps/dashboard/.env.example
  apps/dashboard/src/defer/sendEmail.ts
  apps/dashboard/src/defer/sendEmails.ts
  apps/dashboard/src/lib/components/Course/components/Lesson/Exercise/ViewMode.svelte
  apps/dashboard/src/nodemailer/sendEmail.ts
  apps/dashboard/src/routes/api/email/course/exercise_submission_update/+server.js
  apps/dashboard/src/routes/api/email/course/newsfeed/+server.ts
  apps/dashboard/src/routes/api/email/course/student_prove_payment/+server.js
  apps/dashboard/src/routes/api/email/course/student_welcome/+server.js
  apps/dashboard/src/routes/api/email/course/submission_update/+server.js
  apps/dashboard/src/routes/api/email/course/teacher_student_buycourse/+server.js
  apps/dashboard/src/routes/api/email/course/teacher_student_joined/+server.js
  apps/dashboard/src/routes/api/email/course/teacher_welcome/+server.js
  apps/dashboard/src/routes/api/email/invite/+server.js
  apps/dashboard/src/routes/api/email/verify_email/+server.js
  apps/dashboard/src/routes/api/email/welcome/+server.js
  apps/dashboard/svelte.config.js
  apps/dashboard/tsconfig.json
  pnpm-lock.yaml
  supabase/seed.sql
Labels: core team work

#263 fix: Select dropdown on Edit mode in community page changes height
  apps/dashboard/src/routes/org/[slug]/community/[slug]/+page.svelte
Labels: bug

#261 fix: Made the text input of course description in certificate visible
  apps/dashboard/src/lib/components/Course/components/Ceritficate/Design.svelte
Labels: bug, good first issue

#265 feat: After use clicks "Submit Grade", close the tab
  apps/dashboard/src/lib/components/Course/components/Lesson/Exercise/MarkExerciseModal.svelte
Labels: good first issue

#267 chore: Update hero section of /blog
  apps/classroomio-com/src/lib/Hero/Hero.svelte
  apps/classroomio-com/src/routes/blog/+page.svelte
  apps/classroomio-com/static/hero-bg.svg
Labels: core team work

#266 feat: On landing page move pricing section to its own route /pricing
  apps/classroomio-com/.env.example
  apps/classroomio-com/src/app.css
  apps/classroomio-com/src/lib/Faq/Faq.svelte
  apps/classroomio-com/src/lib/Hero/Hero.svelte
  apps/classroomio-com/src/lib/Navigation/Navigation.svelte
  apps/classroomio-com/src/lib/PageSignupCTA/index.svelte
  apps/classroomio-com/src/routes/+page.svelte
  apps/classroomio-com/src/routes/blog/+page.svelte
  apps/classroomio-com/src/routes/pricing/+layout.ts
  apps/classroomio-com/src/routes/pricing/+page.svelte
Labels: core team work

#269 feat: Added List view to the course page
  apps/dashboard/src/lib/components/Courses/components/Card/index.svelte
  apps/dashboard/src/lib/components/Courses/components/List/Loader.svelte
  apps/dashboard/src/lib/components/Courses/components/List/index.svelte
  apps/dashboard/src/lib/components/Courses/index.svelte
  apps/dashboard/src/lib/components/Courses/store.ts
  apps/dashboard/src/routes/org/[slug]/courses/+page.svelte
Labels: core team work

#275 feat: teachers page
  .github/workflows/cypress.yml
  apps/classroomio-com/src/lib/Faq/Faq.svelte
  apps/classroomio-com/src/lib/Footer/Footer.svelte
  apps/classroomio-com/src/lib/Hero/Hero.svelte
  apps/classroomio-com/src/lib/PageHeader/PageHeader.svelte
  apps/classroomio-com/src/lib/PageSignupCTA/index.svelte
  apps/classroomio-com/src/lib/Pricing/Pricing.svelte
  apps/classroomio-com/src/lib/StudentDashboard/StudentDashboard.svelte
  apps/classroomio-com/src/lib/Testimonial/Testimonial.svelte
  apps/classroomio-com/src/routes/blog/+page.svelte
  apps/classroomio-com/src/routes/oss-friends/+page.svelte
  apps/classroomio-com/src/routes/pricing/+page.svelte
  apps/classroomio-com/src/routes/teach/+layout.ts
  apps/classroomio-com/src/routes/teach/+page.svelte
  apps/classroomio-com/src/routes/teach/register/+page.server.ts
  apps/classroomio-com/static/teach/get-paid.svg
  apps/classroomio-com/static/teach/inspire-learners.svg
  apps/classroomio-com/static/teach/star.svg
  apps/classroomio-com/static/teach/teach-from-anywhere.svg
  apps/classroomio-com/static/teach/teacher-hero.png
  apps/classroomio-com/static/teach/thumbs-up.svg
  apps/classroomio-com/static/teach/user-profile.png
Labels: core team work
