Repository classroomio/classroomio, pull requests merged in 2024-07, with the labels that each got.

#377 fix: bug on gift section of course landing page
  apps/dashboard/src/lib/components/TextEditor/index.svelte
Labels: bug, good first issue

#356 feat: Show all courses available to students
  apps/dashboard/src/lib/components/Courses/api.js
  apps/dashboard/src/lib/components/Courses/components/Card/index.svelte
  apps/dashboard/src/lib/components/Courses/index.svelte
  apps/dashboard/src/lib/components/LMS/SideBar.svelte
  apps/dashboard/src/lib/utils/translations/de.json
  apps/dashboard/src/lib/utils/translations/en.json
  apps/dashboard/src/lib/utils/translations/es.json
  apps/dashboard/src/lib/utils/translations/fr.json
  apps/dashboard/src/lib/utils/translations/hi.json
  apps/dashboard/src/lib/utils/translations/pt.json
  apps/dashboard/src/lib/utils/translations/ru.json
  apps/dashboard/src/lib/utils/translations/vi.json
  apps/dashboard/src/routes/lms/explore/+page.svelte
  apps/dashboard/src/routes/org/[slug]/courses/+page.svelte
  supabase/migrations/20240701085652_show_explore_courses.sql
Labels: core team work

#383 feat: Save functionality using enter
  apps/dashboard/src/lib/components/Course/components/Lesson/NewLessonModal.svelte
Labels: good first issue

#393 fix: dropdown alignment
  apps/dashboard/src/routes/org/[slug]/courses/+page.svelte
Labels: bug

#391 feat: add validation for updating email on profile
  apps/dashboard/src/lib/components/Org/Settings/Profile.svelte
  apps/dashboard/src/lib/utils/functions/validator.js
  apps/dashboard/src/lib/utils/translations/en.json
Labels: bug

#396 fix: lesson widget alignment on page
  apps/dashboard/src/lib/components/Course/components/Lesson/Materials/index.svelte
Labels: bug, good first issue

#395 chore: modifies seed data
  supabase/seed.sql
Labels: backend

#399 feat: RLS on all tables
  apps/dashboard/src/lib/components/Courses/components/Card/index.svelte
  apps/dashboard/src/routes/courses/[id]/lessons/+page.svelte
  supabase/migrations/20240717053936_rls.sql
Labels: enhancement

#398 fix: validation of username and fullname
  apps/dashboard/src/lib/components/Org/Settings/Profile.svelte
  apps/dashboard/src/lib/utils/functions/validator.js
  apps/dashboard/src/lib/utils/translations/en.json
Labels: bug

#295 feat: Certificates Update
  .vscode/settings.json
  apps/backend/certificate.html
  apps/backend/src/utils/certificate.js
  apps/dashboard/src/lib/components/Course/components/Ceritficate/Design.svelte
  apps/dashboard/src/lib/components/Course/components/Ceritficate/StudentCertificate/LockedCertificate.svelte
  apps/dashboard/src/lib/components/Course/components/Ceritficate/StudentCertificate/UnlockedCertificate.svelte
  apps/dashboard/src/lib/components/Course/components/Ceritficate/store.ts
  apps/dashboard/src/lib/components/Course/components/Ceritficate/templates/BlueBadgePattern.svelte
  apps/dashboard/src/lib/components/Course/components/Ceritficate/templates/BlueProfessionalBadge.svelte
  apps/dashboard/src/lib/components/Course/components/Ceritficate/templates/Plain.svelte
  apps/dashboard/src/lib/components/Course/components/Ceritficate/templates/Professional.svelte
  apps/dashboard/src/lib/components/Course/components/Ceritficate/templates/PurpleBadgePattern.svelte
  apps/dashboard/src/lib/components/Course/components/Ceritficate/templates/PurpleProfessionalBadge.svelte
  apps/dashboard/src/lib/components/Courses/api.js
  apps/dashboard/src/lib/components/Org/Community/index.svelte
  apps/dashboard/src/lib/components/RoleBasedSecurity/index.svelte
  apps/dashboard/src/lib/utils/functions/validator.js
  apps/dashboard/src/lib/utils/services/courses/index.ts
  apps/dashboard/src/lib/utils/translations/de.json
  apps/dashboard/src/lib/utils/translations/en.json
  apps/dashboard/src/lib/utils/translations/es.json
  apps/dashboard/src/lib/utils/translations/fr.json
  apps/dashboard/src/lib/utils/translations/hi.json
  apps/dashboard/src/lib/utils/translations/pt.json
  apps/dashboard/src/lib/utils/translations/ru.json
  apps/dashboard/src/lib/utils/translations/vi.json
  apps/dashboard/src/lib/utils/types/index.ts
  apps/dashboard/src/routes/courses/[id]/certificates/+page.svelte
  apps/dashboard/src/routes/lms/+page.svelte
  apps/dashboard/src/routes/lms/community/[slug]/+page.svelte
  apps/dashboard/src/routes/lms/community/ask/+page.svelte
  apps/dashboard/src/routes/lms/explore/+page.svelte
  apps/dashboard/src/routes/lms/mylearning/+page.svelte
  apps/dashboard/src/routes/org/[slug]/community/[slug]/+page.svelte
  apps/dashboard/src/routes/org/[slug]/community/ask/+page.svelte
  apps/dashboard/src/routes/org/[slug]/courses/+page.svelte
  apps/dashboard/static/images/blue-badge-pattern-background.svg
  apps/dashboard/static/images/blue-badge-pattern-badge.svg
  apps/dashboard/static/images/blue-professional-badge.svg
  apps/dashboard/static/images/certificate_theme_blueBadgePattern.png
  apps/dashboard/static/images/certificate_theme_blueProfessionalBadge.png
  apps/dashboard/static/images/certificate_theme_purpleBadgePattern.png
  apps/dashboard/static/images/certificate_theme_purpleProfessionalBadge.png
  apps/dashboard/static/images/purple-badge-pattern-background.svg
  apps/dashboard/static/images/purple-badge-pattern-badge.svg
  apps/dashboard/static/images/purple-professional-badge.svg
  apps/dashboard/static/images/student-certificate-preview.png
  supabase/migrations/20240518054308_new_certificates.sql
Labels: core team work
